<?php
$hasNav = $this->directory->getLogicalPath() || $this->directory->hasMedia();
if ($hasNav) {
    $directoryLink = $directory? 
        $this->url("directory")."?id=".$this->directory->getLogicalPath(): "./";
    $parentLink = $this->directory->getParent()?
        $this->url("directory")."?id=".$this->directory->getParent()->getLogicalPath(): "./";
    $firstMediaLink = $this->directory->hasMedia()? 
        $this->url("media")."?id=".$this->directory->getFirstMedia()->getLogicalPath(): null;
}
?>
            <div class="itemList">
                <h4 class="itemPath"><?php echo $this->logicalPathHtmlLinks; ?></h4>
<?php
if ($hasNav) {
?>
                <nav>
<?php
    if ($this->directory->getParent()) {
?>                     
                    <li class="goback"><a href="<?php echo $parentLink; ?>">Voltar nível</a></li>
<?php
    }
    if ($this->directory->hasMedia()) {
?>                    
                    <li class="openMediaViewer"><a href="<?php echo $firstMediaLink; ?>">Abrir visualizador</a></li>
<?php
    }
?>                                        
                </nav>
<?php
}
if ($this->items) {
?>
                <ul class="items">
<?php
    foreach ($this->items as $item) {
        if (get_class($item) == "FileViewer\Model\Directory") {
            $itemLink = 
                $this->url("directory")."?id=".$item->getLogicalPath();
        }
        else {
            if ($item->getType() == "image")
                $itemLink = 
                    $this->url("media")."?id=".$item->getLogicalPath();
            else
                $itemLink = 
                    $this->url("home").$item->getRelativePath();
        }
?>
                    <li class="<?php echo $item->getType(); ?>File">
                         <a href="<?php echo $itemLink; ?>"><?php echo $item->getShortLabel(); ?></a>
                    </li>
<?php                    
    } // foreach ($items as $item)
?>
                </ul>
<?php
} // if ($items)
else {
?>
                <p class="message error">Não há arquivos ou diretórios</p>
<?php
}
?>
            </div>