<?php
use FileViewer\Configuration\Configuration;

$organizationLabel = Configuration::get("organization","organizationLabel");
$applicationLabel = Configuration::get("organization","applicationLabel");
$developerLabel = Configuration::get("organization","developerLabel");

?>
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title><?php echo $organizationLabel." - ".$applicationLabel; ?></title>
        <link rel="icon" href="<?php echo $this->basePath(); ?>/css/img/favicon.ico" type="image/x-icon">
        <link rel="shortcut icon" href="<?php echo $this->basePath(); ?>/css/img/favicon.ico" type="image/x-icon">
        <link href="<?php echo $this->basePath(); ?>/css/main.php" rel="stylesheet" type="text/css">
        <link 
            href="<?php echo $this->basePath(); ?>/css/high.php" rel="stylesheet" type="text/css" 
            media="screen" 
        >
        <link 
            href="<?php echo $this->basePath(); ?>/css/low.php" rel="stylesheet" type="text/css" 
            media="screen and (max-width: 800px)"
        >
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Droid%20Sans">
<?php 
if (isset($mediaViewerIsOpen) && $mediaViewerIsOpen) { 
?>
        <script src="<?php echo $this->basePath(); ?>/js/mediaViewerIsOpen.js"></script>
<?php 
} 
?>        
    </head>
    <body <?php if (isset($mediaViewerIsOpen) && $mediaViewerIsOpen) { ?>class="mediaViewerIsOpen" <?php } ?>>
        <header>
            <div class="unespHeadings">
                <h1>UNIVERSIDADE ESTADUAL PAULISTA</h1>
                <h2>"JÚLIO DE MESQUITA FILHO"</h2>
            </div>
            <div class="applicationHeadings">
                <h3><?php echo $applicationLabel; ?></h3>
            </div>
            <div class="organizationHeadings">
                <h4><?php echo $organizationLabel; ?></h4>
            </div>
            <div class="pageHeadings">
                <h4><?php echo isset($this->pageTitle) && $this->pageTitle? $this->pageTitle: $applicationLabel; ?></h4>
            </div>
        </header>
        <!--
        <nav class="interactiveNav">
            <h2><a href="#url">Menu</a></h2>
            <ul>
                <li>
                    <h3>Submenu 01</h3>
                    <ul>
                        <li><a href="#url">Item 01</a></li>
                        <li><a href="#url">Item 02</a></li>
                    </ul>
                </li>
                <li>
                    <h3>Submenu 02</h3>
                    <ul>
                        <li><a href="#url">Item 01</a></li>
                        <li><a href="#url">Item 02</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        -->
        <div id="main">
<?php echo $this->content; ?>
            
        </div><!-- div#main -->
        <footer>
            <address><?php echo $organizationLabel."<br>".$developerLabel; ?></address>
            <p id="validators">
                <a href="http://validator.w3.org/check?uri=<?php echo $this->serverUrl(true); ?>">
                    <img src="<?php echo $this->basePath(); ?>/css/img/valid-html5.png" alt="Valid HTML5">
                </a>
                <a href="http://jigsaw.w3.org/css-validator/check/referer">
                    <img src="<?php echo $this->basePath(); ?>/css/img/valid-css3.gif" alt="Valid CSS3" />
                </a>
            </p>
        </footer>
    </body>
</html>    