<?php
$mediaViewerIsOpen = $this->media != null;
if ($mediaViewerIsOpen) {
    $mediaLink = $this->url("home").$this->media->getRelativePath();
    $previousMediaLink = $this->url("home").$this->previousMedia->getUrl();
    $nextMediaLink = $this->url("home").$this->nextMedia->getUrl();
    $numItems = sizeof($this->allItems);
}

$itemPath = "";
foreach ($this->allLogicalPaths as $path => $name)
    $itemPath .= "/<a href=\"".$this->url("home").$path."\">".$name."</a>";
    
$hasNav = $this->directory->getLogicalPath();
if ($hasNav) {
    $directoryLink = $directory? 
        $this->url("home").$this->directory->getUrl(): ".";
    $parentLink = $this->directory->getParent() && $this->directory->getParent()->getLogicalPath()?
        $this->url("home").$this->directory->getParent()->getUrl(): ".";
    $firstMediaLink = $this->directory->hasMedia()? 
        $this->url("home").$this->directory->getFirstMedia()->getUrl(): null;
}
?>
            <div class="itemList">
<?php
if ($mediaViewerIsOpen) {
?>
                <div class="media">
<?php
    if ($media->getType() == "image") {
?>
                    <figure>
                        <img src="<?php echo $mediaLink; ?>" alt="Mídia <?php echo $this->media->getName(); ?>">
                        <figcaption><?php echo $this->media->getName(); ?></figcaption>
                    </figure>
<?php
    }
    else if ($media->getType() == "html5Video") {
?>
                    <video src="<?php echo $mediaLink; ?>" controls autoplay>
                        Seu navegador não suporta o elemento <code>video</code>.
                    </video>
<?php
    }
    else if ($media->getType() == "html5Audio") {
?>
                    <audio src="<?php echo $mediaLink; ?>" controls autoplay>
                        Seu navegador não suporta o elemento <code>video</code>.
                    </audio>
<?php
    }
?>
                    <nav>
                        <ul class="mediaNav">
                            <li class="previous">
                                <a href="<?php echo $previousMediaLink; ?>"><span>Anterior</span></a>
                            </li>
                            <li class="next">
                                <a href="<?php echo $nextMediaLink; ?>"><span>Posterior</span></a>
                            </li>
                        </ul>
                        <ul class="pageNav">
<?php
        for ($i = 0; $i < $numItems; $i++) {
            if ($i%$this->pageSize == 0) {
                $isCurrentPage = 
                    $i <= $this->currentMediaIndex &&
                    $this->currentMediaIndex < $i + $this->pageSize;
                $pageLink = $this->url("home")."media/?id=".$this->allItems[$i]->getLogicalPath();
?>                     
                            <li<?php if ($isCurrentPage) { ?> class="current"<?php } ?>><a href="<?php echo $pageLink; ?>"><?php echo $i/$this->pageSize; ?></a></li>
<?php
            }
        }
?>                      
                        </ul>
                    </nav>
                </div>
<?php
}
if ($hasNav) {
?>
                <nav>
                    <ul>
<?php
    if ($this->directory->getParent()) {
?>                     
                        <li class="goback"><a href="<?php echo $parentLink; ?>">Voltar n&iacute;vel</a></li>
<?php
    }
    if ($mediaViewerIsOpen) {
?>                    
                        <li class="closeMediaViewer"><a href="<?php echo $directoryLink; ?>">Fechar visualizador</a></li>
<?php
    }
    if ($this->directory->hasMedia() && !$mediaViewerIsOpen) {
?>                    
                        <li class="openMediaViewer"><a href="<?php echo $firstMediaLink; ?>">Abrir visualizador</a></li>
<?php
    }
?>                      
                    </ul>
                </nav>
<?php
}
?>
                <h4 class="itemPath"><?php echo $itemPath; ?></h4>
<?php
if ($this->items) {
?>
                <ul class="items">
<?php
    foreach ($this->items as $item) {
        $itemLink = $this->url("home").$item->getUrl();        
        if ($item->getType() == "image") {
            $thumbLink = $this->url("home").$item->getThumbUrl();
?>
                    <li class="<?php echo $item->getType(); ?>File thumb">
                        <figure>
                            <a href="<?php echo $itemLink; ?>"><img src="<?php echo $thumbLink; ?>" alt="Mídia <?php echo $item->getName(); ?>"></a>
                            <figcaption><a href="<?php echo $itemLink; ?>"><?php echo $item->getName(); ?></a></figcaption>
                        </figure>
                    </li>
<?php                  
        }
        else {
?>
                    <li class="<?php echo $item->getType(); ?>File notThumb">
                        <a href="<?php echo $itemLink; ?>"><?php echo $item->getShortLabel(); ?></a>
                    </li>
<?php         
        }
    }
?>
                </ul>
<?php
}
?>
            </div>