<?php

// mediaViewerIsOpen é usada quando o controller Media é chamado
$mediaViewerIsOpen = $this->media != null;
if ($mediaViewerIsOpen) {
    $mediaLink = $this->url("home").$this->media->getDataPath();
    $previousMediaLink = $this->url("home").$this->previousMedia->getUrl();
    $nextMediaLink = $this->url("home").$this->nextMedia->getUrl();
    $numItems = sizeof($this->allItems);
}
?>
<?php
if ($mediaViewerIsOpen) {
?>
                <script> 
               
jQuery(function($) {
    
    function ucfirst(string) {
        return string.charAt(0).toUpperCase() + string.slice(1);
    }
    
    function mediaViewer(src, alt, name, id, total) {
        $(".pageHeadings h4").first().text(name);
        $("#mediaElement").attr("src","<?php echo $this->url("home") ?>" + src);
        $("#mediaElement").attr("alt",alt);
        if ($("#mediaLabel").length)
            $("#mediaLabel").text("Mídia " + (id + 1) + " de " + total);
    }
    
    function mediaLink(event, orientation) {
        event.preventDefault();
        var action = "get" + ucfirst(orientation) + "Media";
        $.post(action, {path: $("#mediaElement").attr("alt")},
            function(data){
                if (data.response == true) {
                    if (data.otherPage == false) {
                        mediaViewer(
                            data.dataPath, data.logicalPath, data.name, data.id, data.numItems
                        );
                        itemChildren = $("#itemList").children();
                        for (i = 0; i < itemChildren.length; i++) {
                            className = itemChildren[i].className;
                            className = className.replace('current','');
                            itemChildren[i].className = className;
                            if (itemChildren[i].id == 'item' + data.id)
                                itemChildren[i].className += ' current';
                        }
                    }    
                    else
                        location.href='<?php echo $this->url("home")."media/?path=";?>' + data.logicalPath;
                }
                else
                    alert('could not update');
            }, 'json');
    }
    
    $("#previousMediaLink").on('click', function(event){mediaLink(event,"previous")});
    $("#nextMediaLink").on('click', function(event){mediaLink(event,"next")});
    
});

$(document).keydown(function(evt) {
    switch (evt.keyCode) {
        case 37:
            $('#previousMediaLink')[0].click();
            break;
        case 39:
            $('#nextMediaLink')[0].click();
            break;
    }
});

                </script>
                <div class="media">
<?php
    if ($this->media->isImage()) {
?>
                    <figure>
                        <img id="mediaElement" src="<?php echo $mediaLink; ?>" alt="<?php echo $this->media->getLogicalPath(); ?>">
                        <figcaption id="mediaLabel"><?php echo "Mídia ".($this->currentMediaIndex + 1)." de ".$numItems; ?></figcaption>
                    </figure>
<?php
    }
    else if ($this->media->isHtml5Video()) {
?>
                    <video id="mediaElement" src="<?php echo $mediaLink; ?>" alt="<?php echo $this->media->getLogicalPath(); ?>" controls autoplay>
                        Seu navegador não suporta o elemento <code>video</code>.
                    </video>
<?php
    }
    else if ($this->media->isHtml5Audio()) {
?>
                    <audio id="mediaElement" src="<?php echo $mediaLink; ?>" alt="<?php echo $this->media->getLogicalPath(); ?>" controls autoplay>
                        Seu navegador não suporta o elemento <code>video</code>.
                    </audio>
<?php
    }
?>
                    <nav>
                        <ul class="mediaNav">
                            <li class="previous">
                                <a href="<?php echo $previousMediaLink; ?>" id="previousMediaLink">Anterior</a>
                            </li>
                            <li class="next">
                                <a href="<?php echo $nextMediaLink; ?>" id="nextMediaLink">Posterior</a>
                            </li>
                        </ul>
<?php
        if ($numItems > $pageSize) {
?>
                        <ul class="pageNav">
<?php
            for ($i = 0; $i < $numItems; $i++) {
                if ($i%$this->pageSize == 0) {
                    $isCurrentPage = 
                        $i <= $this->currentMediaIndex &&
                        $this->currentMediaIndex < $i + $this->pageSize;
                    $pageLink = $this->url("home")."media/?path=".\urlencode($this->allItems[$i]->getLogicalPath());
?>                     
                            <li<?php if ($isCurrentPage) { ?> class="current"<?php } ?>><a href="<?php echo $pageLink; ?>"><?php echo $i/$this->pageSize; ?></a></li>
<?php
                }
            }
?>                      
                        </ul><!-- ul.pageNav -->
<?php
        }
?>                        
                    </nav>
                </div><!-- div.media -->
<?php
}
